### ISSUE TITLE
Formdata values are null instead of empty string

### ISSUE THREAD

**Issue by maheshperi19** [indiepaul/xform#4]
Hi,
Formdata values are coming as null instead of empty string.

**{item_name: , description:, price: null, discount: null}**

I found the issue with type. If i take type as FieldType.numeric, this is happening and also defaultvalue is not setting. It is working fine with FieldType.text

**Comment by indiepaul** [comment]
Hi,
Can you post some code for the null problem, I couldn't replicate that. 
I have published an update that will fix the numeric defaults, try it and let me know if it solves your other problem too.

**Comment by maheshperi19** [comment]
Hi,

Please check this code. Price and discount are numeric types. Default values are not prepopulating and when i submit without entering price and discount, printing null values.

Here is the sample code.

Widget getListViewWidget() {
    return Container(
      height: MediaQuery.of(context).size.height,
      padding: const EdgeInsets.only(left: 20, right: 20),
      child: XForm(
          autoValidate: false,
          key: xFormKey,
          submit: _submit,
          showButtons: false,
          children: <Widget>[
            ListView(shrinkWrap: true, children: <Widget>[
              Text(
                "Item Name",
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
              ),
              this.getSizedBox(boxHeight: 20),
              XTextField(
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context,
                    textColor: kBlackColor,
                    fontSize: 20), // Use your text style here...
                name: "item_name",
                defaultValue: "Test Item",
                required: true,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
              this.getSizedBox(boxHeight: 30),
              Text(
                "Description",
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
              ),
              this.getSizedBox(boxHeight: 20),
              XTextField(
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
                name: "description",
                defaultValue: "Test Desc",
                type: FieldType.text,
                decoration: InputDecoration(border: OutlineInputBorder()),
              ),
              this.getSizedBox(boxHeight: 30),
              Text(
                "Price",
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
              ),
              this.getSizedBox(boxHeight: 20),
              XTextField(
                defaultValue: "150", // value is in rupees
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
                name: "price",
                type: FieldType.numeric,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
              this.getSizedBox(boxHeight: 30),
              Text(
                "Discount",
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
              ),
              this.getSizedBox(boxHeight: 20),
              XTextField(
                defaultValue: "7", // discount value in %
                style: CustomTextStyle.customTitleWithRegularFont(
                    context: context, textColor: kBlackColor, fontSize: 20),
                name: "discount",
                type: FieldType.numeric,
                decoration: InputDecoration(
                  border: OutlineInputBorder(),
                ),
              ),
              this.getSizedBox(boxHeight: 30),
            ]),
          ]),
    );
  }

  Widget getSizedBox({double boxWidth, double boxHeight}) {
    return SizedBox(
      width: boxWidth,
      height: boxHeight,
    );
  }

  _submit(formData) {
    FocusScope.of(context).unfocus();
    print(
        "formData/submit is $formData"); // Here {item_name: Test Item, description: Test Desc, price: null, discount: null}
  }

Not a problem with FieldType.text. But problem with FieldType.numeric

**Comment by indiepaul** [comment]
Your code works, I'm using the current version of the plugin. Update to v0.3.0 and try again.

<img width="909" alt="Screenshot 2020-11-16 at 7 21 52 PM" src="https://user-images.githubusercontent.com/12908076/99286035-fcd88b80-2840-11eb-9c39-775601791d5f.png">
<img width="295" alt="Screenshot 2020-11-16 at 7 22 13 PM" src="https://user-images.githubusercontent.com/12908076/99286071-095ce400-2841-11eb-82be-9da8106f12e1.png">

**Comment by maheshperi19** [comment]
Okay. Thank you. I will check with version v0.3.0 and confirm.

**Comment by maheshperi19** [comment]
Hi,

It is working with v0.3.0. Thank you. Better to provide textInputAction type also for keyboard dismiss. In current scenario, when coming to last text field only, keyboard is dismissing.

**Comment by indiepaul** [comment]
Awesome. and thanks for the suggestion, I'll look into that too.
